name: apptiket
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
    
    
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  curved_navigation_bar: ^1.0.3
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logoflex.png
    - assets/logo/flexy.png
    - assets/logo/
  
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico.ttf
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
